export const INSPECTOR_HTML = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mnemosyne · live memory</title>
<style>:root{color-scheme:dark;font:16px system-ui;background:#0c1016;color:#eef3fa}*{box-sizing:border-box}body{max-width:1080px;margin:auto;padding:32px 20px}h1{font-size:38px;letter-spacing:-1px}p{color:#aebbcf}form,.toolbar{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}input,button{font:inherit;padding:12px;border:1px solid #3c5069;border-radius:8px;background:#172331;color:inherit}input{flex:1;min-width:200px}button{cursor:pointer;background:#265c65}button:disabled{opacity:.4;cursor:default}article{border:1px solid #344051;border-radius:12px;padding:20px;margin:16px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.6 ui-monospace,monospace}.badge{font-size:13px;color:#91ded4}#status{min-height:24px}label{display:flex;gap:8px;align-items:center}label input{min-width:0;flex:none}details{margin-top:16px}summary{cursor:pointer}button:focus-visible,input:focus-visible,summary:focus-visible{outline:3px solid #8becdc;outline-offset:3px}.danger{background:#67363d}@media(max-width:600px){body{padding:20px 14px}h1{font-size:30px}button{min-height:44px}}</style>
<main><span class="badge">MNEMOSYNE / LIVE LOCAL STORE</span><h1>What your agent remembers.</h1><p>Inspect the original evidence, corrections and dependencies in your running memory store.</p>
<form id="connect"><input id="token" type="password" placeholder="Access token" aria-label="Access token" autocomplete="off"><button>Connect</button><button id="disconnect" type="button">Disconnect</button></form>
<p id="scope"></p><form id="search"><input id="query" placeholder="Search memories" aria-label="Search memories"><button>Search</button><button id="refresh" type="button">Browse</button></form>
<div class="toolbar"><label><input id="history" type="checkbox">Include history</label><button id="next" disabled>Next page</button></div><p id="status" role="status" aria-live="polite">Connect to inspect live data. Your token stays in this page's memory.</p><section id="results" aria-label="Memory results"></section></main><script src="/app.js"></script></html>`;

export const INSPECTOR_JS = `'use strict';
const byId=id=>document.getElementById(id);let token='',capabilities=null,cursor,session=0,connection=new AbortController();
function resetConnection(){session++;connection.abort();connection=new AbortController();token='';capabilities=null;cursor=undefined;byId('results').replaceChildren();byId('scope').textContent='';byId('next').disabled=true;}
async function api(path,body){const current=session;const response=await fetch('/v1/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),redirect:'error',signal:AbortSignal.any([connection.signal,AbortSignal.timeout(15000)])});const value=await response.json();if(current!==session)throw new Error('Connection changed.');if(!response.ok)throw new Error(value.error||'Request failed');return value;}
function status(message){byId('status').textContent=message;}
function render(items){byId('results').replaceChildren();for(const item of items){const memory=item.memory||item;const card=document.createElement('article');const badge=document.createElement('div');badge.className='badge';badge.textContent=memory.kind+' · '+memory.status+' · '+memory.trust+' · '+memory.visibility;const content=document.createElement('pre');content.textContent=memory.text;const detail=document.createElement('details');const title=document.createElement('summary');title.textContent='Evidence and provenance';const data=document.createElement('pre');data.textContent=JSON.stringify({id:memory.id,source:memory.source,dependencies:memory.dependencies,createdAt:memory.createdAt,validFrom:memory.validFrom,validUntil:memory.validUntil,metadata:memory.metadata},null,2);detail.append(title,data);card.append(badge,content,detail);
if(capabilities&&capabilities.captureEnabled&&!capabilities.readOnly&&memory.agentId===capabilities.agentId&&memory.status==='active'&&memory.trust!=='verified'&&memory.metadata.advisory!==false&&!['skill','model'].includes(memory.metadata.runtimeType)){const edit=document.createElement('button');edit.textContent='Correct';edit.addEventListener('click',async()=>{if(edit.disabled)return;const text=prompt('Replacement observation',memory.text);if(text===null)return;const reason=prompt('Reason for correction');if(!reason)return;edit.disabled=true;edit.textContent='Saving…';try{await api('correct',{id:memory.id,text,source:memory.source,reason});await browse();status('Correction saved. Dependent advice was invalidated.');}catch(error){status(error.message);}finally{edit.disabled=false;edit.textContent='Correct';}});card.append(edit);}
if(capabilities&&capabilities.allowDestructive&&memory.agentId===capabilities.agentId&&memory.metadata.advisory!==false){const forget=document.createElement('button');forget.className='danger';forget.textContent='Forget';forget.addEventListener('click',async()=>{if(forget.disabled)return;if(!confirm('Purge this memory and content derived from it from this live store?'))return;forget.disabled=true;forget.textContent='Forgetting…';try{await api('forget',{id:memory.id});await browse();status('Memory and its derived content were removed from the live store.');}catch(error){status(error.message);}finally{forget.disabled=false;forget.textContent='Forget';}});card.append(forget);}byId('results').append(card);}}
async function browse(next=false){byId('query').value='';try{const result=await api('inspect',{limit:5,includeInactive:byId('history').checked,...(next&&cursor?{cursor}:{})});cursor=result.nextCursor;byId('next').disabled=!cursor;render(result.items);status(result.items.length+' memories from the live store');}catch(error){status(error.message);}}
byId('connect').addEventListener('submit',async event=>{event.preventDefault();const entered=byId('token').value;byId('token').value='';resetConnection();token=entered;const current=session;try{capabilities=await api('capabilities');byId('scope').textContent=capabilities.workspaceId+' / '+capabilities.agentId+' · '+capabilities.retrieval;await browse();}catch(error){if(current===session){resetConnection();status(error.message);}}});
byId('disconnect').addEventListener('click',()=>{resetConnection();status('Disconnected. Token cleared from this page.');});
byId('search').addEventListener('submit',async event=>{event.preventDefault();try{const results=await api('recall',{query:byId('query').value,limit:20});cursor=undefined;byId('next').disabled=true;render(results);status(results.length+' live matches');}catch(error){status(error.message);}});
byId('refresh').addEventListener('click',()=>browse());byId('history').addEventListener('change',()=>browse());byId('next').addEventListener('click',()=>browse(true));`;
